name = "watch"
main = "src/index.js"
compatibility_date = "2024-01-01"

# 静态资源目录
[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/admin*", "/api/*", "/go/*"]

# KV 绑定
[[kv_namespaces]]
binding = "DATA_KV"
id = "ea6c3cbc73b441968b0db08769f90a0f"
